{{- if .Values.env | len | ne 0 }}
apiVersion: v1
data:
{{- range $k, $v := .Values.env }}
  {{ $k }}: "{{ $v }}"
{{- end }}
kind: ConfigMap
metadata:
  name: {{ include "shell-registry.fullname" . }}
{{- end }}